id = "gruvbox-crisp-themes"
name = "Gruvbox Crisp Themes"
version = "0.1.1"
schema_version = 1
authors = ["Vatsal Sanjay <vatsalsanjay@gmail.com>"]
description = "Custom Gruvbox themes for Zed Editor with crisp high contrast variants"
repository = "https://github.com/VatsalSy/zed-gruvbox_custom_themes"