name: Bump Zed Extension

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Bump version
        uses: huacnlee/zed-extension-action@v1.0.0
        with:
          path: extension.toml
